### ISSUE TITLE
how get public AAPD 

### ISSUE THREAD

**Issue by FeiCoder** [chiennv2000/Label-Correlation-Based-Graph-Convolutional-Network-for-Multi-label-Text-Classification#1]
The AAPD I found in other sources is not complete, how can the author find the complete AAPD

**Comment by chiennv2000** [comment]
Hi, you can download it from here (https://drive.google.com/drive/u/0/folders/1BAv_Qnbd3o9c-5t1tVCpEAeS90CRDXBr)

**Comment by FeiCoder** [comment]
Thank you for your reply and generosity.
